import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";

// Add the weight property to specify the font weights you need
const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "700"],  // Specify the weights you need, e.g., normal (400) and bold (700)
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  weight: ["400", "700"],  // Specify the weights you need for the monospace font
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${robotoMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
